### ISSUE TITLE
Some suggested Improvements/Enhancements

### ISSUE THREAD

**Issue by just5ky** [kamilkosek/jellyplist#32]
These suggestions are based on the last few hours of using the containers. Which didn't go too smoothly.

- [ ] Option to only add songs to Lidarr and trigger a search.
  - Lidarr can use Prowlarr to search and download music in the highest quality.

- [ ] Pin pgsql database to a version, SQL dbs tends to have breaking changes in major upgrades.

- [ ] jellyplist put all the songs in __jellyfin folder, with random names. Can we have it put files album or artist wise.

- [ ] Update the `docker-compose.yml`
  - Volume mapping for `beat` container is missing, it kept looking for Spotify cookies and dies when it didn't find it.

- [ ] Let me rename containers (redis)
  - I use a massive docker-compose stack with 50+ containers, 
  - When I tried to rename the `redis` container, the other container was not able to connect to it.
  - are you hard-coding the redis container name/address?

- [ ] Ability to use exportify.net CSV to import playlist.
- [ ] Utilize `Viperinius/jellyfin-plugin-spotify-import` to match songs, while Jellyplist focuses on downloading.

**Comment by just5ky** [comment]
## compose.yml

```yml
networks:
  jellyplist:

services:
#--------------------------------------------------------------------------------------------#
#                                 Jellyplist                                                 #
#--------------------------------------------------------------------------------------------#
  jellyplist:
    container_name: jellyplist
    image: ghcr.io/kamilkosek/jellyplist:latest
    depends_on: 
      - jellyplist-postgres
      - jellyplist-redis
    ports:
      - "8787:5055"
    networks:
      - jellyplist
      - proxy
    volumes:
      - $DOCKERDIR/jellyplist/cookies.txt:/jellyplist/cookies.txt  # 
      - $DOCKERDIR/jellyplist/open.spotify.com_cookies.txt:/jellyplist/spotify-cookie.txt
      - /mnt/4tb/lidarr:/data/music 
    env_file:
      - .env

  jellyplist-worker:
    container_name: jellyplist-worker
    image: ghcr.io/kamilkosek/jellyplist:latest
    command: ["celery", "-A", "app.celery", "worker", "--loglevel=info"]
    volumes:
      - $DOCKERDIR/jellyplist/cookies.txt:/jellyplist/cookies.txt 
      - $DOCKERDIR/jellyplist/open.spotify.com_cookies.txt:/jellyplist/spotify-cookie.txt
      - /mnt/4tb/lidarr:/data/music
    env_file:
      - .env
    depends_on:
      - jellyplist-postgres
      - jellyplist-redis
    networks:
      - jellyplist

  jellyplist-beat:
    container_name: jellyplist-beat
    image: ghcr.io/kamilkosek/jellyplist:latest
    command: ["celery", "-A", "app.celery", "beat", "--loglevel=info"]
    env_file:
      - .env
    depends_on:
      - jellyplist-postgres
      - jellyplist-redis
    networks:
      - jellyplist
    volumes:
      - $DOCKERDIR/jellyplist/cookies.txt:/jellyplist/cookies.txt 
      - $DOCKERDIR/jellyplist/open.spotify.com_cookies.txt:/jellyplist/spotify-cookie.txt

  jellyplist-redis:
    image: redis:alpine
    container_name: redis   # Tired to rename the container here
    volumes:
      - $DOCKERDIR/jellyplist/redis:/data
    networks:
      - jellyplist

  jellyplist-postgres:
    container_name: postgres-jellyplist
    image: postgres:16.3-alpine  # Pin the version
    environment:
      POSTGRES_USER: ${JELLYPLIST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${JELLYPLIST_POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - $DOCKERDIR/jellyplist/postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - jellyplist
    restart: unless-stopped
```
