### ISSUE TITLE
Cannot make it download even one track. Help appreciated.

### ISSUE THREAD

**Issue by djs7eu3h** [kamilkosek/jellyplist#64]
Worker logs say it downloaded the mp3´s but there is nothin when looking in the container.

Cannot make Jellyplist download even 1 track.

The Playlist folder is created including thumbnail in Jellyfin but zero tracks are in it.

When using image 0.1.7, I can add playlists to "monitored" but the Tasks stay in "pending" state.

When then switching to v0.1.9, I can start the tasks but get the the spotdl timeout 90 while it still says it downloaded the tracks to "/data/music/__jellyplist". 
There are no mp3`s in the container filesystem.

When starting with the v0.1.9 image, the blue button to add a playlist doesn't even work, thats why I start with the 0.1.7 image. (to be able to add a playlist to monitored)

---

**DOCKER-COMPOSE:**

```yaml
services:

  jellyfin:
    image: jellyfin/jellyfin:10.10.3
    container_name: jellyfin
    user: 1000:1000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    
    networks:
      - jellyplist-network
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    volumes:
      - ./jellyfin_data/config:/config
      - ./jellyfin_data/tvshows:/data/tvshows
      - ./jellyfin_data/movies:/data/movies
      - ./jellyfin_data/music:/data/music
    restart: unless-stopped
      
    

  redis:
    image: redis:7-alpine
    container_name: redis
    volumes:
      - redis_data:/data
    networks:
      - jellyplist-network

  postgres:
    container_name: postgres-jellyplist
    image: postgres:17.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - ./jellyplist_pgdata/postgres:/data/postgres
    networks:
      - jellyplist-network
    restart: unless-stopped
    
    
  
  jellyplist:
    container_name: jellyplist
    image: ${image_jellyplist}
    depends_on: 
      - postgres
      - redis
      - jellyfin
    ports:
      - "5055:5055"
    networks:
      - jellyplist-network
    volumes:
      - ./jellyplist_data/cookies.txt:/jellyplist/cookies.txt
      - ./jellyplist_data/open.spotify.com_cookies.txt:/jellyplist/spotify-cookie.txt
      - ./jellyfin_data/music:/data/music
    env_file:
      - .env


networks:
  jellyplist-network:
    driver: bridge
    
volumes:
    postgres:
    redis_data:
```

---

**.ENV:**

```text
###IMAGE_JELLYPLIST = ghcr.io/kamilkosek/jellyplist:v0.1.9
IMAGE_JELLYPLIST = ghcr.io/kamilkosek/jellyplist:0.1.7


POSTGRES_USER = jellyplist
POSTGRES_PASSWORD = jellyplist
SECRET_KEY = Keykeykesykykesky
JELLYFIN_SERVER_URL = http://jellyfin:8096
JELLYFIN_ADMIN_USER = user
JELLYFIN_ADMIN_PASSWORD = password
SPOTIFY_CLIENT_ID = 123456ABCDEF-CHANGEME
SPOTIFY_CLIENT_SECRET = 123456ABCDEF-CHANGEME
JELLYPLIST_DB_HOST = postgres-jellyplist
JELLYPLIST_DB_USER = jellyplist
JELLYPLIST_DB_PASSWORD = jellyplist
MUSIC_STORAGE_BASE_PATH = '/data/music'

### Optional: 
# SPOTDL_PROXY = http://proxy:8080
# SPOTDL_OUTPUT_FORMAT = "/{artist}/{artists} - {title}" # Supported variables: {title}, {artist},{artists}, {album}, Will be joined with to get a complete path

# SEARCH_JELLYFIN_BEFORE_DOWNLOAD = false # defaults to true, before attempting to do a download with spotDL , the song will be searched first in the local library

# START_DOWNLOAD_AFTER_PLAYLIST_ADD = true # defaults to false, If a new Playlist is added, the Download Task will be scheduled immediately

# FIND_BEST_MATCH_USE_FFPROBE = true # Use ffprobe to gather quality details from a file to calculate quality score. Otherwise jellyplist will use details provided by jellyfin. defaults to false. 

#REFRESH_LIBRARIES_AFTER_DOWNLOAD_TASK = true # jellyplist will trigger a music library update on your Jellyfin server, in case you dont have `Realtime Monitoring` enabled on your Jellyfin library. Defaults to false.

#LOG_LEVEL = DEBUG # Defaults to INFO

# SPOTIFY_COOKIE_FILE = '/jellyplist/spotify-cookie.txt' # Not necesarily needed, but if you like to browse your personal recomendations you must provide it so that the new api implementation is able to authenticate

### Lidarr integration
# LIDARR_API_KEY = aabbccddeeffgghh11223344 # self explaining
# LIDARR_URL = http://<your_lidarr_ip>:8686 # too
# LIDARR_MONITOR_ARTISTS = false # If false, only the corresponding album will be set to monitored in lidarr, if true the whole artist will be set as monitored. Be careful in the beginning as you might hammer your lidarr instance and you indexers. Defaults to false
```

---

**Linking issues cannot find anything:**
![image](https://github.com/user-attachments/assets/cdc98f79-faa2-4628-9ac4-6d905b589c01)
