### ISSUE TITLE
Can't get jellyplist to launch. Appears to be issue with redis. Exit on Code 1 through Portainer

### ISSUE THREAD

**Issue by Geoff-eg** [kamilkosek/jellyplist#78]
As title says, I can't get the container to launch. Results:
jellyplist - exited - code 1
postgres-jellyplist - running
redis - exited - code 1

When deploying the container it successfully deploys, but, can't access the published ports, and then noticed the redis failed. Shortly after jellyplist follows. I don't know what I'm missing. 

Confirmed NFS shares are correctly working and the correct folders were created to contain the various containers.

.yml as follows in Portainer Stack

```
services:
  redis:
    image: redis:7-alpine
    container_name: redis
    volumes:
      - /mnt/NFS/Jellyfin/jellyplist_pgdata/redis_data:/data
    networks:
      - jellyplist-network
  postgres:
    container_name: postgres-jellyplist
    image: postgres:17.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - /mnt/NFS/Jellyfin/jellyplist_pgdata/postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - jellyplist-network
    restart: unless-stopped
  
  jellyplist:
    container_name: jellyplist
    image: ${IMAGE}
    depends_on: 
      - postgres
      - redis
    ports:
      - "5055:5055"
    networks:
      - jellyplist-network
    volumes:
      - /mnt/NFS/Jellyfin/jellyplist/cookies.txt:/jellyplist/cookies.txt
      - /mnt/NFS/Jellyfin/jellyplist/open.spotify.com_cookies.txt:/jellyplist/spotify-cookie.txt
      - ${MUSIC_STORAGE_BASE_PATH}:${MUSIC_STORAGE_BASE_PATH}
    env_file:
      - stack.env

networks:
  jellyplist-network:
    driver: bridge

volumes:
    postgres:
    redis_data:
```
