### ISSUE TITLE
How to connect to external database

### ISSUE THREAD

**Issue by Anexgohan** [kamilkosek/jellyplist#8]
so i have an external postgres database in an separate container for databases which is my central database for all apps

the docker compose is this:
```
  # <-_-_-_-_-_-_-_-_-_-_-> Postgres17 <-_-_-_-_-_-_-_-_-_-_-> #
  database_postgres_17:
    # https://hub.docker.com/_/postgres
    # https://www.postgresql.org/docs/14/libpq-envars.html
    container_name: database-postgres-17
    image: postgres:17
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - ./docker-data/database/postgres17:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/
    environment:
      TZ: 'Asia/Kolkata'
      POSTGRES_USER: ${POSTGRES17_POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES17_POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES17_POSTGRES_DB}
      POSTGRES_INITDB_ARGS: ${POSTGRES17_POSTGRES_INITDB_ARGS}
    env_file:
      - .env
    ports:
      - '23306:5432'
    # extra_hosts:
    #   - "postgres:${HOST_IP}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5432 -U ${POSTGRES17_POSTGRES_USER} -d ${POSTGRES17_POSTGRES_DB}"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 5
  # <-_-_-_-_-_-_-_-_-_-_-> \Postgres17 <-_-_-_-_-_-_-_-_-_-_-> #
  ```
  
  how can I connect jellyplist to my database?
